Add abstract aggregate root class
loom/loom-java pull request #28
Opened 2017-05-07 13:33 UTC by mhyeon-lee

AggregateRoot 인터페이스를 구현한 추상 클래스인 AbstractAggregateRoot 를 추가했습니다.

우선 제가 필요하다고 생각한 기준 몇가지로 기능을 만들어 봤으며, 리뷰를 통해 초벌을 다듬으면 될거 같습니다.
저도 몇가지는 어떤 방향이 더 합리적일지 고민이 되는 부분들이 있어서 같이 고민하면 좋을거 같습니다.

논의가 길어질거 같거나 확장적인 이슈는 아래 이슈에 추가하셔도 될거 같습니다.
https://github.com/loom/loom-core/issues/27

마음껏 물어 뜯어 주세요

2017-05-07 13:36 UTC, mhyeon-lee commented on src/test/java/io/loom/core/aggregate/RepositoryTest.java
> +        assertEquals(issue, loadIssue.get());
assertEquals 의 expected 와 actual 이 반대로 되어 있어서 수정했습니다.

2017-05-07 22:41 UTC, LeeKyoungIl commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        return getClass().getSimpleName()
코드를 너무 잘 짜셔서 리뷰 하면서 우와~ 하고 있습니다. 👍 

혹시 말씀 드리는데 

우리 앞으로 String 연산에서 delimiter가 필요한 경우는 
Java8 부터 나온 StringJoiner 또는 StringJoin 을 이용하는것은 어떨까요?

이 부분의 경우 

String stringValue = new StringJoiner(", ")
                .add("id=" + id).add("version=" + version).add("deleted=" + deleted).toString();

        return getClass().getSimpleName()
                + "{"
                + stringValue
                + '}';

요러케. 

한번 의견 드려봅니다. 주말에. 수고하셨어요.

2017-05-07 23:03 UTC, LeeKyoungIl commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        UUID aggregateId = this.getId();
aggregateId 는 아래의 2개의 IF 문에서 공통 필수 조건으로 사용하셨는데요. 
그렇다면 먼저 체크하는것은 어떨까요?

```java
    if (aggregateId != null) {
        throw new NullPointerException("aggregateId is must not be null.");
    }
    if (!aggregateId.equals(event.getAggregateId())) {
        throw new IllegalArgumentException("Applied aggregateId is not equal.");
    }
    if (!this.isValid()) {
        throw new IllegalStateException("Aggregate state is invalid.");
    }
```

2017-05-07 23:38 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        UUID aggregateId = this.getId();
aggregate == null 인 경우는 최초 new 로 인스턴스가 생성된 후에 Created event 가 넘어온 경우라 Exception 을 내면 안되고 pass 시켜야 될거 같아요.

2017-05-07 23:39 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        return getClass().getSimpleName()
넵 수정하겠습니다 감사합니다.
IDE generate 한테 맡기고 별로 신경을 안썼었네요;

2017-05-08 01:35 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        UUID aggregateId = this.getId();
@LeeKyoungIl 아래와 같이 `if (aggregateId != null)` 로 한번 감쌌습니다.

2017-05-08 01:42 UTC, LeeKyoungIl commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        UUID aggregateId = this.getId();
@mhyeon-lee 👍

2017-05-08 01:43 UTC, LeeKyoungIl approved these changes
👍

2017-05-08 01:45 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean valid;
`valid` 필드는 어떤 용도인가요?

2017-05-08 01:49 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private UUID id;
`id` 필드는 `final`인 것이 좋지 않을까요?

```java
private final UUID id;

protected AbstractAggregateRoot(UUID id) {
    if (id == null)
        throw new IllegalArgumentException("The parameter 'id' cannot be null.");

    this.id = id;
}
```

2017-05-08 01:53 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    protected void raise(DomainEvent event) {
`protected` 접근 메서드이니 `event` 매개변수에 대해 `null` 방어 구문이 들어가면 좋겠습니다.

```java
if (event == null)
    throw new IllegalArgumentException("The parameter 'event' cannot be null.");
```

2017-05-08 01:55 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    protected void raise(DomainEvent event) {
네 추가하겠습니다.

2017-05-08 01:58 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private UUID id;
java 생태계의 여러 프레임워크에서 cglib 등을 사용해서 클래스를 상속한 프록시를 만들어 활용하는 경우가 많습니다. 특히 JPA 에서 @Entity 를 이렇게 사용하는데요
그러기 위해서 제약되는 조건이 package-level 이상의 no-args-constructor 를 필요로 하게 됩니다.
no-args-constructor 를 만들어주게 되면 결국 초기화 할 수 없는 필드를 final 로 만들지 못하는 제약이 있습니다.

2017-05-08 01:59 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean deleted;
이 클래스에서 삭제된 상태를 위한 코드를 제공하는 것이 바람직할까요? 예를 들어 `delete()` 메서드를 호출하면 아무 이벤트도 발생하지 않고 읽기 모델이나 연동 서비스는 집합체가 삭제되었다는 것을 알 수 없게 됩니다.

2017-05-08 02:04 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean deleted;
네 그러면 엔티티가 delete 되는 이벤트라는 걸 알 수 있는 방법이 따로 제공되어야 될거 같습니다.
DeleteEvent 라는 인터페이스가 제공되는 방법이 생각나는데 어떤 방법이 좋을까요?

2017-05-08 02:07 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private UUID id;
이벤트 소싱의 집합체가 JPA와 직접 연동될 가능성은 없다고 생각합니다. 아직 확인되지 않은 제약을 위해 Java 언어가 가진 장점을 버리는 것이 좋은 선택인지 모르겠습니다.

2017-05-08 02:07 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean valid;
해당 클래스의 상태가 정상적이지 않을때를 체크하기 위한 값입니다.
event handler 메소드 실행 중에 Exception 이 발생하면 해당 클래스의 상태가 온전하지 않을 수 있습니다.
예를들어 아래의 과정을 거치게 됐을 때, 예외가 발생했는데 Issue 클래스의 title 은 이미 변경되어 있습니다.
이런 방법보다 나이스하게 원복시킬 수 있는 방법이 있으면 더 좋을거 같긴합니다.
그러려면 apply 전에 스냅샷을 뜨고 Exception 이 발생했을때 다시 복구를 시켜야될거 같은데 비용이 클거 같은 생각이 듭니다. 혹시 좋은 아이디어가 있을까요?

``` java
protected void handle(IssueTitleChanged event) {
    this.title = event.getTitle();
    throw new RuntimeException();
}
```

2017-05-08 02:20 UTC, mhyeon-lee commented
이 PR 은 전체적인 방향에 영향을 미치는 PR 이므로 멤버 전원의 approve 후에 merge 하고자 합니다.

2017-05-08 02:30 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean deleted;
이벤트 소싱에서 개체의 삭제 역시 하나의 도메인 이벤트일 뿐입니다. 프레임워크가 특정 유형의 도메인 이벤트를 제공하는 것에 대해서 현재 저는 부정적이고 별도의 논의가 필요하다고 생각합니다.

2017-05-08 02:32 UTC, gyuwon requested changes
몇 가지 수정 및 확인 사항을 댓글로 남깁니다.

2017-05-08 02:56 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean deleted;
네 그러면 우선 delete 와 관련된 코드는 제거하고 별도 논의를 가지는 방향으로 가겠습니다.

2017-05-08 03:05 UTC, gyuwon commented
저는 이 PR이 무겁다는 느낌입니다. 중요한 많은 이슈들이 한 번에 담겨서 모두 논의하고 진행하기 쉽지 않을 것 같습니다. 

이슈나 코드 중에는 서로 독립적인 것들도 있습니다. `equals()`, `hashCode()`, `toString()` 메서드의 경우에는 뒤이은 PR로 분리시켜 핵심 이슈에만 집중할 수 있었으면 하는 바램도 있습니다.

2017-05-08 03:42 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private UUID id;
네 추후에 필요할 때 별도 논의 후 조정하는 방향이 좋겠네요

2017-05-08 03:44 UTC, jwChung requested changes
사소한 수정사항 남겼습니다.

~로 시작하는 코멘트는 수정요청사항이 아니라 질문 및 의견입니다.

2017-05-08 03:44 UTC, jwChung commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    protected void raise(DomainEvent event) {
raise에서는 event 멤버를 사용하는 일이 없군요. 여기는 불필요하다고 `apply` 메소드에 방어구문 추가되는 것이 좋겠습니다.

2017-05-08 03:44 UTC, jwChung commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        }
~ DomainEvent 에서 null을 반환하지 않는다는 보장을 할 수 없습니까? 모든 리턴 값을 null이 될 수 있다고 가정하지는 않을텐데 말이죠.

2017-05-08 03:44 UTC, jwChung commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        if (this.getId() == null) {
~ `this` 접미사는 필드와 속성(getter, setter)에만 쓰나요? validateApplyEvent 메소드는 this가 없네요. 이것도 checkstyle에서 확인해주는지 모르겠네요. 저는 헷깔려서 이 컨벤션 많이 놓치 꺼 같아요.

2017-05-08 03:44 UTC, jwChung commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +            }
fail-fast 가 되기 위해서 `this.isValid()` if 절은 메소드 최상단에 놓여지는 게 좋겠습니다.

아울러, 어떤 경우에 invalid한 시나리오가 생기는지 좀 지켜보면서 개선 방법을 논의해보고 싶네요. 우선 이렇게 진행하다 것에는 이견없습니다.

2017-05-08 03:51 UTC, mhyeon-lee commented
@gyuwon 님께서 이 PR 이 논의 사항도 많고 무겁다는 의견을 주셨고,
작은 단위의 PR 을 올리셨습니다.
https://github.com/loom/loom-core/pull/29

이 PR 은 앞으로 다뤄야할 이슈 및 코드 스타일 등을 제기하고 논의할 수 있는 `샘플` 코드로 정의하고, master 에 merge 하는건 step by step 으로 가는게 좋겠습니다.

2017-05-08 04:01 UTC, gyuwon commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        }
@jwChung Java가 값 형식을 지원하지 않고 `DomainEvent`가 클래스가 아닌 인터페이스라 검사하는 것이 좋지 않을까 싶네요. 조금 장황한 느낌이 들기는 합니다. 만약 `id` 필드가 `null`이 될 수 없는 `final` 필드라면 동일성 여부만 검사해도 되겠네요.

2017-05-08 04:03 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        if (this.getId() == null) {
this 관련 컨벤션에 대해서 특별히 깊게 생각해 보지 않았네요
@jaceshim @LeeKyoungIl 님 혹시 관련해서 자주 사용하는 컨벤션이 있나요?

2017-05-08 04:41 UTC, mhyeon-lee commented
이 PR 은 닫겠습니다. 이후 이슈 논의 및 코드 구현때 참고할 수 있습니다.

2017-05-08 04:41 UTC, closed without merging

2017-05-08 04:56 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean deleted;
https://github.com/loom/loom-core/issues/30 여기서 진행합니다.

2017-05-08 04:57 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +    private boolean valid;
https://github.com/loom/loom-core/issues/31 여기서 논의합니다.

2017-05-08 04:59 UTC, mhyeon-lee commented on src/main/java/io/loom/core/aggregate/AbstractAggregateRoot.java
> +        if (this.getId() == null) {
https://github.com/loom/loom-core/issues/32 여기서 논의합니다.