AbstractDomainEvent의 생성자에서 occurrenceTime 제거
loom/loom-java pull request #41
Opened 2017-05-10 07:08 UTC by jaceshim

AbstractDomainEvent의 생성자에서 occurrenceTime 제거

2017-05-10 07:36 UTC, mhyeon-lee commented
보통 개발자가 Event 인스턴스를 만들때 항상 이벤트가 발생한 시간으로 셋팅하기 때문에 생성자에서 굳이 받을 필요가 없는 점은 공감을 합니다.

그런데, Event 역직렬화시에 occurrenceTime 을 그당시 값으로 셋팅하려면 Reflection 으로 할 수 밖에 없고 Reflection 을 지원하는 Deserializer 만 사용할 수 밖에 없습니다. (물론 대부분의 라이브러리가 Deserializer 를 지원하긴 합니다.) Reflection 을 사용하지 않고도 Deserialize 를 할 수 있도록 지원을 해줘야 한다고 생각합니다.

양쪽을 고려해서 생성자를 수정하는게 아닌, occurrenceTime 을 받지 않는 생성자를 추가하는게 어떨까요?

2017-05-10 07:38 UTC, mhyeon-lee commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +import java.util.UUID;
import 순서가 바뀌면서 checkstyle 검증이 실패한거 같습니다.

2017-05-10 07:41 UTC, gyuwon requested changes
이 PR의 의미가 무엇인지 인지하지 못했습니다.

2017-05-10 07:46 UTC, jaceshim commented
@gyuwon 
이벤트 객체 생성시 전달되는 occurrenceTime 값이
굳이 argument로 전달되지 않아도 생성자에서 할당해도 될것 같아서 변경한건입니다.

하지만 @mhyeon-lee 님이 말씀하신 역직렬화시에 문제가 있을수도 아닐수도 있을것 같아서
occurrentTime을 포함하는 생성자를 추가할 예정입니다~

2017-05-10 07:51 UTC, gyuwon commented
@mhyeon-lee 님이 이미 동일한 이슈로 수정하신 것이 현재 버전입니다.

https://github.com/loom/loom-core/commits/4d621ee447f339a3b20dd57aad582db4732ee816/src/main/java/io/loom/core/event/AbstractDomainEvent.java

2017-05-10 07:57 UTC, jaceshim commented
@gyuwon 
넵 히스토리는 알고 있습니다. 하지만 occurrenceTime의 경우 생성자 argument로 전달하는것은
어찌보면 사용자가 매번 넘겨주지 않아도 되는값인데 매번 전달되게 되는것 같아서
제거한건데요 역직렬화시에 어떤 역직렬화기를 쓰냐에 따라서 이게 이슈가 될 수도 안될수도 있을것 같아서
차라리 occurrentTime을 argument로 받는거와 안받는거 두개의 생성자를 선언하고 사용자들이 
선택적으로 사용하게 하는건 어떨까 싶습니다.

2017-05-10 07:58 UTC, mhyeon-lee commented
@jaceshim 네 그런데 지금 커밋은 occurrencTime 을 안받는 생성자를 추가한게 아니라, 기존 생성자를 수정한거 같습니다.

2017-05-10 07:59 UTC, gyuwon commented
필요성이 높은 디자인인지, 문제의 소지는 없는 디자인인지 이슈를 통해 먼저 논의하는 것은 어떨까요?

2017-05-10 08:28 UTC, jaceshim commented
@gyuwon  네 issue등록해서 처리하는게 좋을것 같습니다.

@mhyeon-lee 지금 PR버전은 수정이 맞구요~ 명현님 말데로 역직렬화시에 문제될 소지가 있을수도 있기에 occurrentTime을 받는거와 안받는거 두개를 지원하도록 수정해서 commit하겠습니당~

2017-05-11 04:35 UTC, jaceshim commented
본 PR은 close하겠습니다.

2017-05-11 04:35 UTC, closed without merging