DomainEvent 에 canSetHeaderProperties 를 추가합니다.
loom/loom-java pull request #64
Opened 2017-07-15 22:59 UTC by mhyeon-lee

DomainEvent 에 이미 headerProperties 가 설정되어 있는데 다른 VersionedEntity 로 값을 바꾸지 않도록 체크 메소드를 추가합니다.

추가로 `setHeaderProperties` 수행시 해당 체크 메소드로 검사하는 로직을 보완합니다.

2017-07-16 03:17 UTC, gyuwon requested changes

2017-07-16 03:17 UTC, gyuwon commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +import java.lang.reflect.Field;
`java.lang.reflect.Field` 클래스를 사용하는 테스트 케이스는 `AbstractDomainEventSpecs` 클래스의 API가 아닌 구현에 의존합니다. 정보 숨김(information hiding)이 깨져서 운영 코드와 테스트 케이스가 강하게 결합되었다는 의미입니다. 가능하면 테스트 케이스가 API에만 의존하도록 하는 것이 어떨까요?

2017-07-16 03:20 UTC, gyuwon commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +    public void canSetHeaderProperties_aggregateId_not_null()
`canSetHeaderProperties_returns_false_when_aggregateId_has_value`나 유사하게 변경해 설명력을 높이는 것이 어떨까요?

2017-07-16 03:23 UTC, mhyeon-lee commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +    public void canSetHeaderProperties_aggregateId_not_null()
네 다른 테스트 케이스 이름들도 변경하겠습니다.

2017-07-16 03:26 UTC, mhyeon-lee commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +import java.lang.reflect.Field;
아래 테스트 케이스에서 보셨듯이, 개발자가 API 를 사용하지 않고 reflect 를 사용해서 값을 셋팅했을 경우를 테스트 하기 위해서 사용했습니다.

정상적이지 않은 상황에 대한 방어가 잘되는지를 확인하는 테스트인데, 좀 더 좋은 방법이 있을까요?

2017-07-16 03:42 UTC, gyuwon commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +import java.lang.reflect.Field;
지금의 불안함은 공용 API(생성자, `setHeaderProperties` 메서드)가 아닌 방법으로 개체 상태를 변경한 상황을 고려하는 것이 원인이라고 생각되는데요. 이런 상황은 클라이언트 코드가 마치 지금의 테스트 케이스처럼 정보 숨김을 깨고 API 내부를 들여다보고 방어구문을 회피했다는 뜻입니다. 저는 이런 디자인에 의해 계약되지 않은, 혹은 더 나아가 악의적인, 접근을 고려한 테스트가 필요하지 않으며 원천적으로는 가능하지도 않다고 생각합니다.

2017-07-16 03:46 UTC, mhyeon-lee commented on src/test/java/io/loom/core/event/AbstractDomainEventSpecs.java
> +import java.lang.reflect.Field;
네 설명 감사합니다.
관련된 테스트 케이스들은 제거하도록 하겠습니다.

2017-07-16 04:35 UTC, gyuwon commented
**우선 저는 이 PR에 반대하는 입장은 아니라는 것을 먼저 말씀 드립니다. 만약 그랬다면 #63 역시 반대했을 겁니다.**

얼마 전 Michael Feathers의 [Converting Queries to Commands](https://michaelfeathers.silvrback.com/converting-queries-to-commands)를 읽었는데 영감을 받았습니다. 조회(query)와 명령(command)의 조합을 명령으로(종국에는 이벤트 처리기로) 리팩터하는 내용입니다. 결과적으로 추상화 수준은 높아지고 설계 복잡도는 낮아집니다.

이 PR이 의도하는 클라이언트의 코드가

```java
if (domainEvent.canSetHeaderProperties()) {
    domainEvent.setHeaderProperties(aggregate);
}
```

Michael Feathers가 묘사하는 조회와 명령의 논리곱 상황이 아닌가 싶습니다. 다시 말해 우리가 Michael Feathers의 결론에서 서론으로 뒤돌아 가고 있는지도 모른다는 뜻입니다. 만약 그게 맞다면 `canSetHeaderProperties` 메서드를 추가하기 보다는 `setHeaderProperties` 메서드의 역할과 이름을 리팩터하는 것이 더 좋은 방법이겠죠.

저는 이 PR을 사소한 부분들만 검토한 후에 승인/ 거절 여부는 다른 분들께 넘기겠습니다. :-)

2017-07-16 05:08 UTC, jaceshim commented
규원님의 영감을 저도 좀 느껴보고 싶네요~ :)

전 이미 header가 설정 되어 있는 여부를 사용자가 핸들링 해야 하나? 에 대해 조금 생각해봅니다.

설정 가능여부를 판단할때 이미 설정되어 있는 경우 Exception을 throws 할거라면 canSetHeaderProperties() 접근 지정자를 private으로 변경해서 내부적으로 사용하면 어떨까요?

@gyuwon
만약 setHeaderProperties 메소드명을 리팩토링 하신다면 어떻게 해보고 싶으세요? 예를 한 번 보고 싶습니당~

2017-07-16 05:14 UTC, mhyeon-lee commented
네 저도 얼마전에 @gyuwon 님이 공유해 주신 링크를 재미있게 읽었습니다.
링크 글의 내용 처럼 메소드 이름을 잘 지어서 조회(query)와 명령(command) 의 조합 명령으로 통합하는 방법은 장점도 많이 있지만 상황에 따라 판단하기 모호한 method가 될 수도 있다고 생각했습니다.

제 개인적인 의견을 몇가지 적어보겠습니다.

조회(query)와 명령(command)를 하나의 메소드로 통합하면, 명령을 받았을때 현재 상태가 받아들이기 적절할 때만 변경을 수행하고 그렇지 않을땐 아무것도 하지 않게 됩니다.
`클라이언트는 너의 상태가 변하든 안변하든 나는 관심이 없다. 나는 너에게 명령(command) 만 내릴 뿐이다.` 라는 관점으로 사용하면서 클라이언트와 메시지를 주고 받는 단계도 감소하고, 복잡도도 많이 낮아집니다.

하지만 위와 같은 통합에서 단점은 클라이언트가 대상의 변경 결과에 관심이 있을 때는 좀 더 복잡해질 수 있을거 같습니다. command 를 수행한 후에 변경 수행 됐는지를 확인하는 query 를 수행해야 될거 같습니다.
코드로 예를 들면,

``` java
domainEvent.setHeaderProperties(aggregate);      // 통합된 메소드명으로 적절하지 않지만 우선 기존이름으로..
if (!domainEvent.getAggregateId().equals(aggregate.getId()) {
     throw new xxxException();
}
```

그럼 DomainEvent 에 `setHeaderProperties` 를 수행하는 클라이언트 입장에서 `header 를 변경해라` 라고 명령(Command) 를 내리고 끝일지, 정말 넘겨준 VersionedEntity 의 id 로 변경이 됐는지 확인이 필요할지 고민해봐야 될거 같습니다.

저의 의견은, DomainEvent 를 메시지로 publish 해야 하는 클라이언트 입장에서 event 의 aggregateId 는 중요한 값일거 같습니다. 이 확인이 없으면 AggregateRoot 가 다른 aggregateId 를 가진 Event 를 publish 할 수 있는 위험이 생길거 같습니다.

* 위의 의견들은 개인적으로 생각한 부분이기 때문에 잘못 생각한 부분이 있으면 정정해주시고 다른 의견이 있으시면 의견주시기 바랍니다.

2017-07-16 05:23 UTC, mhyeon-lee commented
@jaceshim 
네 저도 이 부분을 처음에는 private 으로 하려다가 public 으로 뺀 이유는 `setHeaderProperties` 를 사용하는 클라이언트가 이걸 수행할 수 있는지 판단할 수 있는 api 가 필요하다고 생각 됐기 때문입니다.

`setHeaderProperties` 를 수행할 수 있는지 여부를 판단하는 메소드가 없다면 클라이언트는`setHeaderProperties` 를 실행해서 발생되는 Exception 을 catch 해서 해당 프로세스를 계속 진행할지 판단해야 될거 같습니다.

AbstractAggregateRoot 에 raise 메소드가 구현될 때 다음과 같이 구현될 수 있겠습니다.

``` java
protected void raise(DomainEvent domainEvent) {
    if (domainEvent.canSetHeaderProperties) {
          domainEvent.setHeaderProperties(this);
    }
    // do something...
    this.pendingEvents.add(domainEvent);
}
```

canSetHeaderProperties 가 private 라 접근할 수 없다면 다음과 같이 될거 같습니다.

``` java
protected void raise(DomainEvent domainEvent) {
    try {
        domainEvent.setHeaderProperties(this);
    } catch(IllegalStateException e) {
        if (!this.getId().equals(domainEvent.getAggregateId())) {
             throw e;
        }
    }
    // do something...
    this.pendingEvents.add(domainEvent);
}
```

더 좋은 방법이 있으면 의견주시면 감사하겠습니다.

2017-07-16 15:39 UTC, gyuwon commented
@mhyeon-lee 

다음 예를 생각해보죠.

```java
public void appendZero(List<Integer> numbers) {
    // Guard clause here.
    numbers.add(1);
    // Should I check all elements of 'numbers'?
}
```

우리는 일반적으로 `numbers`의 사전 상태와 사후 상태를 검사하지 않습니다. 왜 일까요? 저는 그것이 OOP의 추상화라고 생각합니다. `appendZero` 메서드의 책임은 `numbers`에 적절한 메시지를 보내는 것으로 끝납니다.

그리고 `try-catch` 코드를 보여주셨는데 저는 두 가지 의문이 듭니다.

1. `try-catch` 블럭이 왜 필요한가?
1. `canSetHeaderProperties` 공용 메서드의 존재가 `try-catch` 블럭의 필요성에 영향을 미치는가?

연산 중 예외가 발생할 때 이것을 처리해야 할 책임은 연산 시작점이 우선적으로 가집니다. 웹 응용프로그램이라면 HTTP 처리기이고 메시지 중심 프로세스라면 메시지 처리기가 되겠죠. 그런데 `setHeaderProperties` 메서드가 예외를 던질 때 `AbstractAggregateRoot`가 예외를 처리해야할 이유가 보여주신 코드로는 충분히 설명되지 않는 것 같습니다.

2017-07-16 23:16 UTC, mhyeon-lee commented
@gyuwon 
### 먼저 try-catch 에 대해서 설명하자면,

- 말씀하신대로 저도 AbstractAggregateRoot 가 예외를 처리해야할 한다고 생각하지 않습니다. 그래서 command 를 수행할 수 있는지 사전 검사가 필요하지 않을까 생각됩니다. 

### Exception 과 사전-사후 상태 검사

- `appendZero` 예시로 의견을 주신대로 OOP 추상화가 잘된 경우 명령(command) 만 내리고, 사전/사후 검사가 필요 없다는 것에 동의합니다.
- 그런데 명령을 내릴때 대상의 상태에 따라 Exception 이 발생할 수 있는 여지가 있습니다.
- Exception 이 클라이언트의 메시지 잘못이 아니라 대상 객체의 상태라면 그 상태를 체크할 수 있는 방법을 클라이언트한테 알려줘서 메시지 전송 판단을 할 수 있게 해줘야 될거 같습니다.
- @gyuwon 님이 주신 링크에서는 명령(Command)와 조회(Query) 를 조합한 메소드를 만들어 대상 객체가 command 를 받아 들일 수 없을 때 Exception 을 내는것이 아닌 아무것도 하지 않는 방법을 소개하고 있습니다.
- 이 메소드는 클라이언트가 명령을 내리고 난 후 결과에 관심이 없을때는 적절한거 같지만, 결과에 관심이 있는 경우에는 사전 상태 검사를 직접 하거나, 사후 검사를 해야합니다.

--- 여기까지가 위의 질문들에 대한 저의 의견이었고 추가 의견을 내겠습니다.

- 추가적으로 드는 생각이 명령(command)와 조회(Query) 를 조합한 메소드로 만들었을 때, 이 메소드를 실행한 클라이언트가 사후 결과에 관심을 가질 필요가 없다고 생각이 바꼈습니다.
- 다만, DomainEvent 에 aggregateId 가 적절하게 셋팅되었는지에 대한 확인의 역할 및 시점은 AggregateRoot 가 event 를 publish 할때 인거 같습니다.

2017-07-16 23:26 UTC, mhyeon-lee commented
@gyuwon 
### 먼저 try-catch 에 대해서 설명하자면,

- 말씀하신대로 저도 AbstractAggregateRoot 가 예외를 처리해야할 한다고 생각하지 않습니다. 위의 코드는 상태에 따라 Exception 을 발행하는 `setHeaderProperties` 를 실행하기 전에 사전 검사를 하지 않는다면 이렇게 될거 같다는 예제였습니다. (특정 주장을 하고자 하는 코드는 아니었습니다.)
그래서 command 를 수행할 수 있는지 사전 검사가 필요하지 않을까 생각됩니다. 

### Exception 과 사전-사후 상태 검사

- `appendZero` 예시로 의견을 주신대로 OOP 추상화가 잘된 경우 명령(command) 만 내리고, 사전/사후 검사가 필요 없다는 것에 동의합니다.
- 그런데 현재의 `setHeaderProperties` 의 경우 명령을 내릴때 대상의 상태에 따라 Exception 이 발생할 수 있는 여지가 있습니다.
- Exception 원인이 클라이언트의 메시지 잘못이 아니라 대상 객체의 상태라면 그 상태를 체크할 수 있는 방법을 클라이언트한테 알려줘서 메시지 전송을 할 것인지 판단 할 수 있게 해줘야 될거 같습니다.
- @gyuwon 님이 주신 링크에서는 명령(Command)와 조회(Query) 를 조합한 메소드를 만들어 대상 객체가 command 를 받아 들일 수 없을 때 Exception 을 내는것이 아닌 아무것도 하지 않는 방법을 소개하고 있습니다.
- 이 메소드는 클라이언트가 명령을 내리고 난 후 결과에 관심이 없을때(일반적인)는 적절한거 같지만, 결과에 관심이 있는 경우에는 사전 상태 검사를 직접 하거나, 사후 검사를 해야합니다.

--- 여기까지가 위의 질문들에 대한 저의 의견이었고 추가 의견을 내겠습니다.

- 추가적으로 드는 생각이 명령(command)와 조회(Query) 를 조합한 메소드로 만들었을 때, 이 메소드를 실행한 클라이언트가 사후 결과에 관심을 가질 필요가 없다고 생각이 바꼈습니다.
- 다만, DomainEvent 에 aggregateId 가 적절하게 셋팅되었는지에 대한 확인의 역할 및 시점은 AggregateRoot 가 event 를 publish(또는 pending) 할때 인거 같습니다.

2017-07-17 00:02 UTC, mhyeon-lee commented
결론적으로 이 PR 은 닫고 `setHeaderProperties` 메소드를 다음과 같이 변경해볼까 합니다.

``` java
public void onRaise(VersionedEntity versionedEntity) {
    // header properties 가 셋팅되어있지 않다면 값 셋팅
    // header properties 가 이미 셋팅되어 있는데 aggregateId, version 이 일치하면 아무것도 하지 않음
    // header properties 가 이미 셋팅되어 있는데 aggregateId, version 이 다르면 Exception
}
```

2017-07-17 01:07 UTC, jaceshim commented
canSetHeaderProperties는 현재 시점에선 도출되지 않아도 무관한 행위 (공개되어야 할 행위) 이나 setHeaderProperties내의 검증 로직을 의미가 명확하게 드러나는 메소드로 추출한 리팩토링 관점에선 괜찮다고 봅니다.

2017-07-17 01:51 UTC, gyuwon commented
@mhyeon-lee 

말씀하신 내용 이해했습니다. 잘못된 집합체 식별자와 버전에 대한 검증은 이벤트가 저장소에 기록되기 직전, 혹은 그 이전 어딘가에 위치하면 적절할 것 같습니다.

2017-07-17 01:55 UTC, mhyeon-lee commented
그럼 두분이 동의하신거 같아 이 PR 은 닫고 `setHeaderProperties` 를 수정하는 방향으로 다시 올리도록 하겠습니다.

2017-07-17 01:55 UTC, closed without merging